live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "MesloLGL Nerd Font Mono"
style = "Bold"

[font.italic]
family = "MesloLGL Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGL Nerd Font Mono"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.85

[window.padding]
x = 18
y = 16
